- name: Install node
  apt:
    name: ["nodejs", "npm"]

- name: Install node libraries
  npm: 
    name: "{{ item }}"
    global: true
  loop:
    - n
    - pm2

- name: Switch to Node14
  shell: n 14